general:
steps:
  gctsDeploy:
    host: 'http://hana4poc.zwtkfpvhnzsehekvcftg5kfdud.rx.internal.cloudapp.net:8002'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'dineshfujitsu-gctsrepo'
    remoteRepositoryURL: 'https://github.com/Dineshfujitsu/gCTSRepo.git'
    role: 'TARGET'
    vSID: 'S4D'
    branch: 'main'
    scope: 'CRNTCOMMIT'
    rollback: false
  gctsExecuteABAPUnitTests:
    host: 'http://hana4poc.zwtkfpvhnzsehekvcftg5kfdud.rx.internal.cloudapp.net:8002'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'dineshfujitsu-gctsrepo'
  gctsRollback:
    host: 'http://hana4poc.zwtkfpvhnzsehekvcftg5kfdud.rx.internal.cloudapp.net:8002'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'dineshfujitsu-gctsrepo'
